'use client';

import Image from 'next/image';
import { useEffect, useState } from 'react';
import type { PropertyMarketReport, ReportAsset, ReportSection } from '@/features/property-report/types';

type ReportImageProps = { asset: ReportAsset; className?: string; priority?: boolean };

function ReportImage({asset, className = '', priority = false}: ReportImageProps) {
  const [src, setSrc] = useState(asset.src);
  useEffect(() => setSrc(asset.src), [asset.src]);
  return <div className={`property-report-image ${className} ${asset.status === 'MISSING' ? 'property-report-image-missing' : ''}`}><Image src={src} alt={asset.alt} fill sizes="(max-width: 768px) 100vw, 50vw" priority={priority} loading="eager" unoptimized onError={() => setSrc((current) => current === asset.fallbackSrc ? current : (asset.fallbackSrc ?? current))} /><span className="property-report-image-status">{asset.status === 'AVAILABLE' ? 'MOCK VISUAL' : asset.status}</span></div>;
}

const money = (value: number) => `${value.toFixed(1)} 萬`;
const unitPrice = (value: number) => `${value.toFixed(1)} 萬/坪`;

function PageFrame({section, children, className = ''}: {section: ReportSection; children: React.ReactNode; className?: string}) {
  return <article className={`property-report-page report-surface-light ${className}`} data-report-section={section.id}><div className="property-report-page-inner"><div className="property-report-page-heading"><div><p className="property-report-eyebrow">{section.eyebrow}</p><h2>{section.title}</h2></div><span className="property-report-page-number">{String(section.order).padStart(2, '0')}</span></div>{children}<p className="property-report-conclusion">{section.conclusion}</p></div></article>;
}

export function PropertyReportPage({report, section, presentation = false}: {report: PropertyMarketReport; section: ReportSection; presentation?: boolean}) {
  const {property, marketSummary, mapSummary, lifestyleSummary, comparisonSummary, propertyInsight} = report;
  if (section.id === 'cover') return <article className={`property-report-page property-report-cover ${presentation ? 'property-report-presentation-page' : ''}`} data-report-section="cover"><div className="property-report-cover-overlay"><div className="property-report-cover-brand"><ReportImage asset={report.logo} className="property-report-logo" priority /></div><div className="property-report-cover-copy"><p className="property-report-eyebrow">E.X REALTY · CLIENT PRESENTATION</p><h1>{property.title}</h1><p className="property-report-cover-location">{property.district} · {property.community}</p><p className="property-report-cover-positioning">{property.targetCustomer}的市場定位與生活圈價值提案</p></div><div className="property-report-cover-footer"><span>{report.brand.companyName}</span><span>{report.agent.name}</span></div></div><ReportImage asset={report.propertyImages[0]} className="property-report-cover-image" priority /></article>;
  if (section.id === 'overview') return <PageFrame section={section}><div className="property-report-overview-grid"><div className="property-report-overview-copy"><p className="property-report-lead">{property.address} 的條件整理，先讓客戶看懂空間與價格。</p><div className="property-report-stat-grid"><div><small>展示總價</small><strong>{money(property.totalPrice)}</strong></div><div><small>單價</small><strong>{unitPrice(property.unitPrice)}</strong></div><div><small>坪數</small><strong>{property.areaPing.toFixed(1)} 坪</strong></div><div><small>格局</small><strong>{property.rooms}</strong></div><div><small>屋齡</small><strong>{property.age} 年</strong></div><div><small>樓層</small><strong>{property.floor}</strong></div></div><div className="property-report-points"><h3>物件特色</h3><ul>{report.sellingPoints.map((point) => <li key={point}>{point}</li>)}</ul></div></div><div className="property-report-overview-images"><ReportImage asset={report.propertyImages[1] ?? report.propertyImages[0]} /><ReportImage asset={report.propertyImages[2] ?? report.propertyImages[0]} /></div></div><div className="property-report-floorplan-row"><div><p className="property-report-eyebrow">FLOORPLAN</p><h3>空間配置</h3></div><ReportImage asset={report.floorplan} className="property-report-floorplan" /></div></PageFrame>;
  if (section.id === 'market-analysis') return <PageFrame section={section}><div className="property-report-metric-row"><div><small>平均單價</small><strong>{unitPrice(marketSummary.averageUnitPrice)}</strong></div><div><small>成交筆數</small><strong>{marketSummary.transactionCount} 筆</strong></div><div><small>價格區間</small><strong>{marketSummary.lowestUnitPrice.toFixed(1)}–{marketSummary.highestUnitPrice.toFixed(1)}</strong><span>萬/坪</span></div><div><small>平均屋齡</small><strong>{marketSummary.averageBuildingAge.toFixed(1)} 年</strong></div></div><div className="property-report-market-grid"><div className="property-report-trend"><div className="property-report-subheading"><h3>近一年價格趨勢</h3><span>單價 / 萬坪</span></div><div className="property-report-trend-bars">{marketSummary.trend.map((point) => <div className="property-report-trend-point" key={`${point.date}-${point.price}`}><div className="property-report-trend-bar" style={{height: `${Math.max(12, Math.min(100, (point.price / Math.max(marketSummary.highestUnitPrice, 1)) * 100))}%`}}><span>{point.price.toFixed(1)}</span></div><small>{point.date}</small></div>)}</div></div><div className="property-report-market-table"><div className="property-report-subheading"><h3>近期成交摘要</h3><span className="property-report-source-badge">MOCK DATA</span></div><table><thead><tr><th>日期</th><th>樓層</th><th>坪數</th><th>單價</th></tr></thead><tbody>{marketSummary.recentTransactions.map((transaction) => <tr key={transaction.id}><td>{transaction.transactionDate}</td><td>{transaction.floor}</td><td>{transaction.areaPing.toFixed(1)}</td><td>{unitPrice(transaction.unitPrice)}</td></tr>)}</tbody></table></div></div></PageFrame>;
  if (section.id === 'area-map') return <PageFrame section={section}><div className="property-report-map-layout"><ReportImage asset={mapSummary.mapImage} className="property-report-map-image" /><div className="property-report-map-copy"><p className="property-report-lead">{mapSummary.region.city} {mapSummary.region.district} · {mapSummary.region.name}</p><div className="property-report-map-stats"><div><small>平均單價</small><strong>{unitPrice(mapSummary.region.averagePrice)}</strong></div><div><small>成交量</small><strong>{mapSummary.region.transactionCount} 筆</strong></div><div><small>年增幅</small><strong>+{mapSummary.region.growthRate.toFixed(1)}%</strong></div><div><small>熱度</small><strong>{mapSummary.region.popularityScore}</strong></div></div><h3>生活圈標籤</h3><div className="property-report-chip-row">{mapSummary.region.lifestyleTags.map((tag) => <span key={tag}>{tag}</span>)}</div><h3>熱門社區</h3><ul className="property-report-plain-list">{mapSummary.region.popularCommunities.map((community) => <li key={community}>{community}</li>)}</ul></div></div><p className="property-report-source-note">MOCK DATA · 區域地圖為展示用示意，不代表即時地理服務。</p></PageFrame>;
  if (section.id === 'lifestyle') return <PageFrame section={section}><div className="property-report-lifestyle-layout"><div className="property-report-lifestyle-copy"><div className="property-report-score"><span>生活圈總分</span><strong>{lifestyleSummary.score.overallScore}</strong><small>/ 100</small></div><p className="property-report-lead">{lifestyleSummary.insight}</p><div className="property-report-lifestyle-cards">{lifestyleSummary.categories.map((category) => <div key={category.label}><small>{category.label}</small><strong>{category.value}</strong><span>{category.score} 分</span></div>)}</div><p className="property-report-audience-note">{lifestyleSummary.audience}</p></div><ReportImage asset={lifestyleSummary.image} className="property-report-lifestyle-image" /></div><div className="property-report-nearby-row">{lifestyleSummary.nearbyPlaces.slice(0, 5).map((place) => <div key={place.id}><strong>{place.name}</strong><span>{place.distance}m · {place.description}</span></div>)}</div><p className="property-report-source-note">MOCK DATA · Lifestyle Score 為規則式展示計算。</p></PageFrame>;
  if (section.id === 'comparison') return <PageFrame section={section}><div className="property-report-comparison-grid"><div className="property-report-comparison-card property-report-comparison-card-subject"><span>本案社區</span><h3>{comparisonSummary.subject.community}</h3><strong>{unitPrice(comparisonSummary.subject.averageUnitPrice)}</strong><dl><div><dt>成交筆數</dt><dd>{comparisonSummary.subject.transactionCount}</dd></div><div><dt>平均總價</dt><dd>{money(comparisonSummary.subject.averageTotalPrice)}</dd></div><div><dt>平均坪數</dt><dd>{comparisonSummary.subject.averageAreaPing.toFixed(1)} 坪</dd></div></dl></div><div className="property-report-comparison-vs">VS</div><div className="property-report-comparison-card"><span>比較社區</span><h3>{comparisonSummary.comparison?.community ?? '區域平均'}</h3><strong>{comparisonSummary.comparison ? unitPrice(comparisonSummary.comparison.averageUnitPrice) : '待補資料'}</strong>{comparisonSummary.comparison && <dl><div><dt>成交筆數</dt><dd>{comparisonSummary.comparison.transactionCount}</dd></div><div><dt>平均總價</dt><dd>{money(comparisonSummary.comparison.averageTotalPrice)}</dd></div><div><dt>平均坪數</dt><dd>{comparisonSummary.comparison.averageAreaPing.toFixed(1)} 坪</dd></div></dl>}</div></div><div className="property-report-comparison-highlight"><span>價格差異</span><strong>{comparisonSummary.unitPriceDifference >= 0 ? '+' : ''}{comparisonSummary.unitPriceDifference.toFixed(1)} 萬/坪 · {comparisonSummary.unitPriceDifferencePercent >= 0 ? '+' : ''}{comparisonSummary.unitPriceDifferencePercent.toFixed(1)}%</strong><p>{comparisonSummary.marketPosition}</p></div></PageFrame>;
  if (section.id === 'sales-positioning') return <PageFrame section={section}><div className="property-report-positioning-header"><div><p className="property-report-eyebrow">CONSULTANT SUMMARY</p><h3>{propertyInsight.title}</h3></div><div className="property-report-score small"><span>Demo Generated Score</span><strong>{propertyInsight.score.overallScore}</strong></div></div><p className="property-report-insight">{propertyInsight.summary}</p><div className="property-report-positioning-grid"><div><small>Target Customer</small><strong>{report.targetCustomer}</strong><p>以客戶生活情境切入，讓價格討論建立在需求之上。</p></div><div><small>Selling Points</small><ul>{report.sellingPoints.map((point) => <li key={point}>{point}</li>)}</ul></div><div><small>Sales Strategy</small><strong>{report.salesStrategy}</strong><p>建議以市場資料與生活圈價值交互驗證。</p></div></div><span className="property-report-source-badge">Demo Generated Insight</span></PageFrame>;
  return <PageFrame section={section} className="property-report-contact-page"><div className="property-report-contact-layout"><div className="property-report-contact-copy"><p className="property-report-eyebrow">LET&apos;S TALK ABOUT THE NEXT MOVE</p><h3>把市場理解，帶進下一次選擇。</h3><p className="property-report-lead">這份報告是展示版提案素材，期待在實際需求、預算與生活方式之間，協助客戶找到更清楚的答案。</p><div className="property-report-contact-details"><strong>{report.contact.agent}</strong><span>{report.contact.company} · {report.contact.branch}</span><span>{report.contact.phone}</span><span>{report.contact.address}</span></div></div><div className="property-report-contact-media"><ReportImage asset={report.agent.portrait} className="property-report-agent-image" /><ReportImage asset={report.qrCode} className="property-report-qr" /><ReportImage asset={report.logo} className="property-report-logo contact-logo" /></div></div><div className="property-report-contact-footer"><span>{report.brand.footerText}</span><span>{report.sourceLabels.join(' · ')}</span></div></PageFrame>;
}
