import {forwardRef} from 'react';
import {compareTransactionToCommunity} from '@/features/real-price/community-analysis';
import {mockBranding,type ProposalBranding} from '@/features/real-price/branding';
import type {CommunitySummary, RealEstateTransaction} from '@/features/real-price/types';

export const TransactionProposalCard = forwardRef<HTMLDivElement,{transaction:RealEstateTransaction;summary:CommunitySummary;branding?:ProposalBranding}>(({transaction,summary,branding=mockBranding},ref) => {
  const comparison = compareTransactionToCommunity(transaction,summary);
  const comparisonText = `${comparison.unitPriceDifferencePercent >= 0 ? '+' : ''}${comparison.unitPriceDifferencePercent.toFixed(1)}%`;
  const comparisonTone = comparison.direction === 'above' ? 'text-emerald-200' : comparison.direction === 'below' ? 'text-orange-200' : 'text-slate-200';
  return <article ref={ref} className="aspect-video w-full overflow-hidden rounded-xl border border-amber-300/25 bg-[radial-gradient(circle_at_85%_10%,rgba(244,201,106,.2),transparent_28%),linear-gradient(135deg,#0a1323,#172b49)] p-4 text-white sm:p-6"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-amber-300 text-xs font-black text-slate-950">{branding.logo}</span><div><p className="text-[9px] tracking-[.16em] text-amber-100/80">{branding.companyName}</p><p className="mt-0.5 text-[10px] text-slate-400">成交案例分析</p></div></div><span className="rounded-full border border-emerald-300/30 bg-emerald-300/10 px-2 py-1 text-[9px] text-emerald-100">MOCK DATA</span></div><div className="mt-4 grid grid-cols-[1.2fr_.8fr] gap-4 sm:mt-6"><div><p className="text-sm font-semibold text-blue-100 sm:text-lg">{transaction.community}</p><p className="mt-1 text-[10px] text-slate-400">成交日期 {transaction.transactionDate} · {transaction.floor} · {transaction.areaPing} 坪</p><p className="mt-3 text-2xl font-bold text-amber-100 sm:text-4xl">{transaction.unitPrice.toFixed(1)} <span className="text-xs font-medium sm:text-sm">萬/坪</span></p><p className="mt-1 text-[10px] text-slate-300 sm:text-xs">總價 {transaction.totalPrice.toLocaleString()} 萬 · 屋齡 {transaction.buildingAge} 年</p></div><div className="rounded-lg border border-white/10 bg-slate-950/30 p-3"><p className="text-[9px] text-slate-400">市場比較</p><p className="mt-2 text-[10px] text-slate-300">社區平均</p><p className="text-sm font-semibold sm:text-lg">{summary.averageUnitPrice.toFixed(1)} 萬/坪</p><p className="mt-2 text-[10px] text-slate-300">本案差異</p><p className={`text-lg font-bold sm:text-2xl ${comparisonTone}`}>{comparisonText}</p></div></div><div className="mt-3 flex items-end justify-between border-t border-white/10 pt-2 text-[9px] text-slate-400 sm:mt-5"><span>{branding.agentName} · {branding.phone}</span><span>資料來源：Mock Data</span></div></article>;
});

TransactionProposalCard.displayName = 'TransactionProposalCard';
