import type { Role } from '@/types/auth';
export type NavItem={id:string;title:string;subtitle:string;description:string;route:string;icon:string;category:string;allowedRoles:Role[];status:'active'|'beta'|'planned'|'disabled';version:string};
const navigationItems: Omit<NavItem, 'subtitle'>[]=[
{id:'real-price-map',title:'區域地圖分析',description:'以 Mock Data 展示高雄區域行情、生活標籤與市場洞察。',route:'/tools/real-price/map',icon:'MapPinned',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'1.2'},
{id:'product-tour',title:'產品導覽',description:'以六步導覽了解展示版平台價值。',route:'/tour',icon:'Compass',category:'Demo',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'1.1'},
{id:'public-showcase',title:'產品展示',description:'對外產品能力展示入口',route:'/showcase',icon:'Presentation',category:'Demo',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'1.0'},
{id:'platform-demo',title:'互動 Demo',description:'公開展示七步房產分析與行銷提案流程',route:'/demo',icon:'Presentation',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.9'},
{id:'production',title:'行政製作中心',description:'榮譽圖與公告圖製作工作台',route:'/admin/production',icon:'PanelsTopLeft',category:'行政',allowedRoles:['ADMIN','MEDIA','MANAGER'],status:'beta',version:'0.2'},
{id:'asset-library',title:'共用素材庫',description:'管理 LOGO、人物、背景與模板資產',route:'/assets/library',icon:'Images',category:'共用',allowedRoles:['ADMIN','MEDIA','MANAGER'],status:'planned',version:'0.2'},
{id:'real-price',title:'房產資料工具',description:'實價登錄查詢與市場行情展示',route:'/tools/real-price',icon:'ChartNoAxesCombined',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'property-report',title:'房產市場智慧報告',description:'將物件、行情、區域與銷售定位整理成客戶報告。',route:'/tools/property-report',icon:'FileText',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'1.3'},
{id:'community-market',title:'社區行情分析',description:'比較社區成交摘要與價格趨勢',route:'/tools/real-price/community',icon:'ChartColumnIncreasing',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'community-compare',title:'社區行情比較',description:'建立雙社區比較與提案素材',route:'/tools/real-price/compare',icon:'GitCompareArrows',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'proposal-studio',title:'市場分析提案中心',description:'以模板組合社區、比較與成交案例素材',route:'/tools/real-price/proposal',icon:'PanelsTopLeft',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'realty-demo',title:'Realty Data Tools Demo',description:'快速載入生活圈案例與品牌化提案',route:'/tools/real-price/demo',icon:'Presentation',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'realty-demo-presentation',title:'AI 房產分析 Demo',description:'五分鐘主管展示流程與完整市場報告。',route:'/tools/real-price/demo/presentation',icon:'Presentation',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'realty-showcase',title:'Realty Data Tools Showcase',description:'主管展示版產品入口與 Demo 報告下載。',route:'/tools/real-price/showcase',icon:'Presentation',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'location-intelligence',title:'生活圈智慧分析',description:'以 Mock Data 展示周邊機能、生活圈分數與銷售洞察。',route:'/tools/location-intelligence',icon:'MapPinned',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.3'},
{id:'property-intelligence',title:'物件智慧分析',description:'整合 Mock 市場、生活圈、銷售洞察與 Proposal Ready 摘要。',route:'/tools/property-analysis',icon:'Building2',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.3'},
{id:'property-marketing-studio',title:'房產行銷內容',description:'將智慧案件分析轉為多平台房仲行銷文案。',route:'/tools/property-marketing',icon:'Megaphone',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.5'},
{id:'creative-studio',title:'創意設計中心',description:'將房仲行銷內容套入固定社群模板並建立 Mock 預覽。',route:'/tools/creative-studio',icon:'Palette',category:'Realty Data Tools',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.6'},
{id:'case-studies',title:'成功案例',description:'整理可複用的成交故事',route:'/admin/case-studies',icon:'BookOpen',category:'行政',allowedRoles:['ADMIN','MANAGER'],status:'planned',version:'0.2'},
{id:'award-graphics',title:'榮譽與成交圖',description:'建立團隊榮譽視覺素材',route:'/admin/award-graphics',icon:'Award',category:'行政',allowedRoles:['ADMIN','MEDIA'],status:'planned',version:'0.2'},
{id:'presentations',title:'PPT 簡報編制',description:'管理會議與訓練簡報',route:'/admin/presentations',icon:'Presentation',category:'行政',allowedRoles:['ADMIN','MEDIA'],status:'planned',version:'0.2'},
{id:'property-summary',title:'案件整理彙整',description:'集中整理物件資料',route:'/admin/property-summary',icon:'FolderKanban',category:'行政',allowedRoles:['ADMIN','SALES','MANAGER'],status:'planned',version:'0.2'},
{id:'onboarding',title:'新人教材',description:'新人訓練資源入口',route:'/learning/onboarding',icon:'GraduationCap',category:'共用',allowedRoles:['ADMIN','MANAGER','VIEWER'],status:'planned',version:'0.2'},
{id:'free-ai',title:'免費 AI 工具',description:'安全的外部工具連結',route:'/tools/free-ai',icon:'Sparkles',category:'共用',allowedRoles:['ADMIN','SALES','MEDIA','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'prospecting',title:'開發廣告圖',description:'文案、版型、預覽與匯出流程',route:'/sales/prospecting-graphics',icon:'Megaphone',category:'業務',allowedRoles:['SALES','MANAGER'],status:'planned',version:'0.3'},
{id:'property-marketing',title:'房屋文案與廣告設計',description:'整理物件行銷輸入輸出',route:'/sales/property-marketing',icon:'Home',category:'業務',allowedRoles:['SALES','MANAGER'],status:'planned',version:'0.3'},
{id:'social-copy',title:'社群文案編製',description:'常用社群內容模板',route:'/sales/social-copy',icon:'MessageSquareText',category:'業務',allowedRoles:['SALES','MANAGER'],status:'planned',version:'0.3'},
{id:'social-design',title:'社群廣告設計',description:'規劃社群視覺工作流',route:'/sales/social-design',icon:'Palette',category:'業務',allowedRoles:['SALES','MEDIA','MANAGER'],status:'planned',version:'0.3'},
{id:'script-assistant',title:'AI 話術助手',description:'常見情境話術整理',route:'/sales/script-assistant',icon:'MessagesSquare',category:'業務',allowedRoles:['SALES','MANAGER'],status:'planned',version:'0.2'},
{id:'video-production',title:'影片製作',description:'素材到剪輯任務的流程骨架',route:'/media/video-production',icon:'Video',category:'影音',allowedRoles:['MEDIA','SALES','MANAGER'],status:'beta',version:'0.1'},
{id:'booking',title:'拍攝預約',description:'預留 Booking Studio 整合入口',route:'/media/booking',icon:'CalendarDays',category:'影音',allowedRoles:['MEDIA','SALES','MANAGER'],status:'planned',version:'0.5'},
{id:'mortgage',title:'房貸試算',description:'純前端的月付金試算',route:'/tools/mortgage-calculator',icon:'Calculator',category:'工具',allowedRoles:['ADMIN','SALES','MANAGER','VIEWER'],status:'beta',version:'0.2'},
{id:'prompt-library',title:'Prompt Library',description:'集中管理可複用提示詞',route:'/tools/prompt-library',icon:'Library',category:'工具',allowedRoles:['ADMIN','SALES','MEDIA','MANAGER','VIEWER'],status:'planned',version:'0.2'},
{id:'tasks',title:'任務派工',description:'預留跨團隊工作流',route:'/tasks',icon:'ListTodo',category:'共用',allowedRoles:['ADMIN','SALES','MEDIA','MANAGER'],status:'planned',version:'0.5'}];

const navigationSubtitles: Record<string, string> = {
  'real-price-map': 'Area Map Intelligence',
  'product-tour': 'Product Tour',
  'public-showcase': 'Product Showcase',
  'platform-demo': 'Interactive Demo',
  production: 'Admin Production Studio',
  'asset-library': 'Asset Library',
  'real-price': 'Real Price Intelligence',
  'property-report': 'Property Market Report',
  'community-market': 'Community Market Analysis',
  'community-compare': 'Community Comparison',
  'proposal-studio': 'Proposal Studio',
  'realty-demo': 'Realty Data Tools Demo',
  'realty-demo-presentation': 'Client Presentation',
  'realty-showcase': 'Realty Data Tools Showcase',
  'location-intelligence': 'Location Intelligence',
  'property-intelligence': 'Property Intelligence',
  'property-marketing-studio': 'Property Marketing',
  'creative-studio': 'Creative Studio',
  'case-studies': 'Case Studies',
  'award-graphics': 'Award Graphics',
  presentations: 'Presentation Builder',
  'property-summary': 'Property Summary',
  onboarding: 'Onboarding Learning',
  'free-ai': 'Free AI Tools',
  prospecting: 'Prospecting Graphics',
  'property-marketing': 'Property Marketing Copy',
  'social-copy': 'Social Copy',
  'social-design': 'Social Design',
  'script-assistant': 'Sales Script Assistant',
  'video-production': 'Video Production',
  booking: 'Media Booking',
  mortgage: 'Mortgage Calculator',
  'prompt-library': 'Prompt Library',
  tasks: 'Task Workspace',
};

export const navigation: NavItem[] = navigationItems.map((item) => ({ ...item, subtitle: navigationSubtitles[item.id] ?? 'Operations Module' }));
